### ISSUE TITLE
Add README.md files for each data-structure/algorithm

### ISSUE THREAD

**Issue by erilyth** [erilyth/Standard-Datastructures#1]
Add documentation to each of the Data-structure/Algorithm next to the codes so a new user can understand them better. Each folder corresponds to one concept, so a README.md file within each folder would be quite helpful. 
(You can start off by just adding the documentation to one of the algorithms/data-structure)

**Comment by codegagan** [comment]
@erilyth What exactly to document about an algorithm ?

**Comment by erilyth** [comment]
@codegagan A small description of what the algorithm/datastructure does and what it is used for which a person could read up and understand how the algorithm works. Once they understand what it is and how it works then they can go through the code and understand the implementation aspects as well.
(Lets consider Heaps for example, https://www.tutorialspoint.com/data_structures_algorithms/heap_data_structure.htm, something similar to the description provided there would be great!)

**Comment by anabastos** [comment]
Can you assign me?

**Comment by erilyth** [comment]
@anabastos You can start working on it, just submit a PR and it should be fine.

**Comment by avi-jain** [comment]
I'd like to help out with this too. Will work on the Stacks, Queues and Heaps part

**Comment by erilyth** [comment]
@avi-jain Sure! Go ahead!

**Comment by sbshah97** [comment]
Hey @erilyth I'd like to work on Graphs if that's fine with you!

**Comment by erilyth** [comment]
@salman-bhai Sorry, the README for graphs was already done, but if you have any improvements I would be glad to add them in.

**Comment by jatinrajani** [comment]
@erilyth 
I have added README for SORTING as well as BST if that's fine with you.Sorry I didn't asked you before. #7 #8

**Comment by erilyth** [comment]
@jatinrajani Merged! Thanks :)

**Comment by jatinrajani** [comment]
Thanks!!

**Comment by jedian** [comment]
Hey @erilyth, i would like to contribute with segment tree's README, if that's okay.

#17
