### ISSUE TITLE
Inline documentation

### ISSUE THREAD

**Issue by erilyth** [erilyth/Standard-Datastructures#2]
Some in-line comments need to be added to the code, which could help people understand the code better.

**Comment by sbshah97** [comment]
Hey, I'd like to help in contributing if that's okay with you. I do have certain experience in Data Structures and I'd be glad to help you out.

**Comment by erilyth** [comment]
@salman-bhai Sure! Go ahead and submit a PR.

**Comment by sbshah97** [comment]
**Inline Documentation added** #21
